version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: community-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: community
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: community-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql-data:
