server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://community-mysql:3306/community?serverTimezone=Asia/Seoul
    username: root
    password: KGm?pwZ%y[15
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
